import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'file-upload-with-preview/dist/style.css';
import { createClient } from "@/utils/supabase/server";
import { redirect } from 'next/navigation'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();

  console.log(data);
  if (data.user == null) {
    return redirect('/login');
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
