import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'file-upload-with-preview/dist/style.css';
import { createClient } from "@/utils/supabase/server";
import { redirect } from 'next/navigation'
import Image from 'next/image';
// import { User } from '@supabase/supabase-js';
// import { createContext } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const UserContext = createContext<User | null>(null);
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();
  if (data.user == null) {
    return redirect('/login');
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <UserContext.Provider value={data.user}> */}
          <Image className="m-10" alt="Logo" src="/logo.png" width={100} height={100}/>
          {children}
        {/* </UserContext.Provider> */}
      </body>
    </html>
  );
}
